language: python
sudo: required
python:
- '2.7'
services:
- docker
script:
- "./build"
deploy:
  - provider: releases
    file:
    - "$(find tmp/*.noarch.rpm)"
    skip_cleanup: true
    api-key:
      secure: bKPvXvZNhoKRJT1qpvRbxKlRAVga9TOeghqI5tiycch+BFdVcxgYGQ2A/lh1WtFo5exxaNSRB9lqjkx4WQcoBP8eMBdTq3E8nGRKfcwk68XBVWtfdcAt9b3Y3TDnJRoA9HKsKkVzdNWlSAd6hOAI8X+sLjcximsjP1/HZalxoImcWwz7GNFQJTQdmeG6Zh+8G+23/w17K1JtiZyyqtQIhg9pY4e45GP/AQk6kqGRcn2q0yaznCvXvZziAMloXfcL7QgP/HAKTUh1zA+UvBre9URejz17EpAvSMSuzhk8ihMy57POx/P+hiUnncQNx+HweOZzSgzwaCsPvIGgzu9ZJpNSIx9i3cEb0MF1aGF7AkurarBZVlU1oNVxBSNNZdVgtfLsLfjAttYBQC0zo2ct35pkVGR/r9GnKLEgCMNN5hHunTC0GfTK0PcamvJt5gmuh62x0fGa0+LZCa1EQyBr2kzfr481hHonC4mgHGFa5eU4IR+4CpcRhRvAz1Vcm+djRIqbH2Jp75vS6pj3N2cazjxEer2YvOzwNaGR3lDjjyl3//bUCgfym1yr3NMXQlbLO7he5URawUMmAIBBpPg814o+c2GVNLYBo4+oE4/VcEcw2+0uJ4/sRZnb1RxAfHar28Qu0yeZv0JdBy0svyOsKpRQocTCVTK3KDtTD5tPgZk=
